version: '3.3'

services:
  
  vuelearn:
    build:
      context: vue-learn
      dockerfile: ./Dockerfile
      #restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - openid

  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports: 
      - "9021:3000"
    networks: 
      - openid
    
networks:
  openid:
    driver: bridge
